### ISSUE TITLE
Layer upload fails with an error related to permissions

### ISSUE THREAD

**Issue by capooti** [cga-harvard/worldmap#112]
When uploading a new shapefile in the staging we get this error:

Traceback (most recent call last):
  File "/home/ubuntu/cga-worldmap/geonode/layers/views.py", line 185, in layer_upload
    metadata_upload_form=form.cleaned_data["metadata_upload_form"])
  File "/home/ubuntu/cga-worldmap/geonode/layers/utils.py", line 524, in file_upload
    defaults=defaults
  File "/home/ubuntu/pyenv/worldmap/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/pyenv/worldmap/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 389, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/home/ubuntu/pyenv/worldmap/local/lib/python2.7/site-packages/django/db/models/query.py", line 407, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/home/ubuntu/pyenv/worldmap/local/lib/python2.7/site-packages/django/db/models/query.py", line 439, in _create_object_from_params
    obj = self.create(**params)
  File "/home/ubuntu/pyenv/worldmap/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 381, in create
    return super(MultilingualQuerySet, self).create(**kwargs)
  File "/home/ubuntu/pyenv/worldmap/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ubuntu/pyenv/worldmap/local/lib/python2.7/site-packages/polymorphic/models.py", line 74, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/home/ubuntu/pyenv/worldmap/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ubuntu/pyenv/worldmap/local/lib/python2.7/site-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/ubuntu/pyenv/worldmap/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/ubuntu/cga-worldmap/geonode/base/models.py", line 1251, in resourcebase_post_save
    instance.set_missing_info()
  File "/home/ubuntu/cga-worldmap/geonode/base/models.py", line 1079, in set_missing_info
    self.set_default_permissions()
  File "/home/ubuntu/cga-worldmap/geonode/security/models.py", line 146, in set_default_permissions
    remove_object_permissions(self)
  File "/home/ubuntu/cga-worldmap/geonode/security/models.py", line 636, in remove_object_permissions
    raise e
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In my development instance upload works properly, so it could be something related with permission tables?

**Comment by capooti** [comment]
Looking at the code block, the error is generated by geofence. Therefore I guess we have something misconfigured in geofence settings.

**Comment by capooti** [comment]
This is fixed.
